# fly.toml app configuration file generated for herald-scraper-bot

app = 'herald-scraper-bot'
primary_region = 'sea' # Singapore region, change as needed

[build]

[env]
  # Add your environment variables here or set them via flyctl secrets

# Since this is a one-time job/cronjob rather than a web service, 
# we'll run it as a machine that can be triggered manually or scheduled
[processes]
  scraper = "python lambda_function.py"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

# Run the scraper once per day
[processes]
  scheduler = "while true; do python lambda_function.py; sleep 86400; done"  # Run every 24 hours