'use strict';
const $ = s => document.querySelector(s);
let snapshot = null, busy = false, requestId = 0;
const escape = s => String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function inline(text){return escape(text).replace(/&lt;:([a-zA-Z0-9_]+):[0-9]+&gt;/g,(_,name)=>snapshot?.emojis?.[name]?`<img class="discord-emoji" src="${snapshot.emojis[name]}" alt="${name}" title="${name.replaceAll('_',' ')}">`:`:${name}:`).replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/\[([^\]]+)\]\((https:\/\/[^\s)]+)\)/g,'<a href="$2" target="_blank" rel="noopener noreferrer">$1</a>');}
function markdown(text){return text.split('\n').map(line=>line.startsWith('## ')?`<h2>${inline(line.slice(3))}</h2>`:line.startsWith('### ')?`<h3>${inline(line.slice(4))}</h3>`:line.startsWith('-# ')?`<div class="subtext">${inline(line.slice(3))}</div>`:`<p>${inline(line)||'<br>'}</p>`).join('');}
function el(tag, cls, text){const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;}
function media(url, cls, description){const name=(url||'').replace('attachment://','');if(!snapshot.files[name])return el('div','empty-media',description||'Image unavailable in offline fixture');const img=el('img',cls);img.src=snapshot.files[name];img.alt=description||name;img.addEventListener('error',()=>img.replaceWith(el('div','empty-media','Image unavailable')));return img;}
function component(c){let node;
 switch(c.type){
 case 17:node=el('div','v2-container');if(c.accent_color)node.style.setProperty('--accent','#'+c.accent_color.toString(16).padStart(6,'0'));for(const ch of c.components||[])node.append(component(ch));return node;
 case 10:node=el('div','v2-text');node.innerHTML=markdown(c.content||'');return node;
 case 14:node=el('hr','v2-separator');if(c.divider===false)node.style.border=0;return node;
 case 9:node=el('div','v2-section');const content=el('div','v2-text');for(const ch of c.components||[])content.append(component(ch));node.append(content);if(c.accessory)node.append(component(c.accessory));return node;
 case 11:return media(c.media?.url,'v2-thumbnail',c.description||'Net-worth lead thumbnail');
 case 12:node=el('div','v2-gallery');for(const item of c.items||[])node.append(media(item.media?.url,'',item.description||'Net-worth lead chart'));return node;
 case 1:node=el('div','v2-actions');for(const ch of c.components||[])node.append(component(ch));return node;
 case 2:node=el(c.url?'a':'button','v2-button'+(c.style===1?' primary':c.url?' link':''),c.label||c.emoji?.name||'Button');if(c.url){node.href=c.url;node.target='_blank';node.rel='noopener noreferrer';node.onclick=e=>{e.preventDefault();const note=el('div','notice','This is a synthetic match ID. Live match links are disabled in the offline lab.');$('#message').prepend(note);};node.append(el('span','',' ↗'));}else{node.dataset.customId=c.custom_id;node.disabled=!!c.disabled;node.onclick=()=>act({action:'component',custom_id:c.custom_id});}return node;
 case 3:return select(c);
 default:return el('div','empty-media',`Unsupported Discord component ${c.type}`);
 }
}
function select(c){const wrap=el('div','v2-select'),trigger=el('button','select-trigger'),label=el('span','selected-text'),menu=el('div','select-menu');let selected=c.options.filter(o=>o.default).map(o=>o.value);label.textContent=selected.length?c.options.filter(o=>o.default).map(o=>o.label).join(', '):c.placeholder||'Select';trigger.append(label);trigger.dataset.customId=c.custom_id;trigger.disabled=!!c.disabled;trigger.setAttribute('aria-haspopup','listbox');trigger.setAttribute('aria-expanded','false');trigger.setAttribute('aria-label',c.placeholder||'Select');menu.setAttribute('role','listbox');menu.setAttribute('aria-label',c.placeholder||'Select options');menu.hidden=true;const multi=c.max_values>1;menu.setAttribute('aria-multiselectable',String(multi));const close=()=>{menu.hidden=true;trigger.setAttribute('aria-expanded','false');};trigger.onclick=()=>{const open=menu.hidden;document.querySelectorAll('.select-menu').forEach(m=>m.hidden=true);document.querySelectorAll('.select-trigger').forEach(t=>t.setAttribute('aria-expanded','false'));menu.hidden=!open;trigger.setAttribute('aria-expanded',String(open));if(open){menu.classList.remove('opens-up');const box=menu.getBoundingClientRect();if(box.bottom>innerHeight-12&&trigger.getBoundingClientRect().top>box.height)menu.classList.add('opens-up');}};
for(const o of c.options){const option=el('button','select-option');option.setAttribute('role','option');option.setAttribute('aria-selected',String(selected.includes(o.value)));const check=el('span','option-check',selected.includes(o.value)?'✓':'');option.append(check,el('span','',o.label));option.onclick=()=>{if(multi){if(selected.includes(o.value))selected=selected.filter(v=>v!==o.value);else selected.push(o.value);option.setAttribute('aria-selected',String(selected.includes(o.value)));check.textContent=selected.includes(o.value)?'✓':'';}else{close();act({action:'component',custom_id:c.custom_id,values:[o.value]});}};menu.append(option);}
if(multi){const apply=el('button','select-apply','Apply selection');apply.onclick=()=>{close();act({action:'component',custom_id:c.custom_id,values:selected});};menu.append(apply);}wrap.onkeydown=e=>{if(e.key==='Escape'){close();trigger.focus();}if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();if(menu.hidden)trigger.click();const options=[...menu.querySelectorAll('button')];const current=options.indexOf(document.activeElement);const next=e.key==='ArrowDown'?(current+1)%options.length:(current<=0?options.length-1:current-1);options[next]?.focus();}};wrap.append(trigger,menu);return wrap;}
function embed(e){const root=el('section','classic-embed');root.style.setProperty('--accent','#'+(e.color||0x5865f2).toString(16).padStart(6,'0'));if(e.title){const title=el('div','embed-title');title.innerHTML=inline(e.title);root.append(title);}if(e.description){const desc=el('div','v2-text');desc.innerHTML=markdown(e.description);root.append(desc);}const fields=el('div','embed-fields');for(const f of e.fields||[]){const field=el('div','embed-field'+(f.inline?' inline':'')),name=el('div','embed-field-name'),value=el('div','v2-text');name.innerHTML=inline(f.name);value.innerHTML=markdown(f.value);field.append(name,value);fields.append(field);}root.append(fields);if(e.footer)root.append(el('div','embed-footer',e.footer.text));return root;}
function render(data){snapshot=data;$('#message').replaceChildren();if(data.message){const notice=el('div','notice',data.message);notice.setAttribute('role','alert');if(data.error){const retry=el('button','','Retry');retry.onclick=()=>reset(false,'normal');notice.append(retry);}$('#message').append(notice);}for(const c of data.components||[])$('#message').append(component(c));for(const e of data.embeds||[])$('#message').append(embed(e));$('.private-note').textContent=data.embeds?'Scheduled reporter · Classic embed snapshot':'◈ Only you can see this · Simulator';$('#component-label').textContent=data.embeds?'Classic embeds':'Components V2';$('#component-budget').textContent=data.embeds?`${data.embeds.length} / 10`:`${data.budget?.components??'—'} / 40`;$('#text-budget').textContent=`${data.budget?.text??'—'} / ${data.embeds?'6,000':'4,000'}`;$('#interaction-state').textContent=data.error?'Error shown':data.events?.includes('acknowledged')?'ACK → render':'Ready';if(data.modal)openModal(data.modal);}
async function act(data){if(busy)return;busy=true;const id=++requestId;$('#interaction-state').textContent='Loading';const prev=snapshot;$('#message').replaceChildren();const loading=el('div','loading');loading.innerHTML='<i></i><i></i><i></i> Herald is thinking…';loading.setAttribute('role','status');$('#message').append(loading);try{if($('#slow').checked)await new Promise(r=>setTimeout(r,1800));const response=await fetch('/api',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...data,revision:prev?.revision})});const result=await response.json();if(id!==requestId)return;if(!response.ok)throw Error(result.message||'Simulator request failed');render(result);}catch(error){if(id===requestId)render({...prev,error:true,message:error.message});}finally{if(id===requestId)busy=false;}}
function reset(focus=false,scenario=$('#scenario').value){$('#scenario').value=scenario;return act({action:'reset',scenario,focus});}
function openModal(data){const fields=$('#modal-fields');fields.replaceChildren();for(const row of data.components||[]){for(const f of row.components||[]){const input=el('input');input.id=f.custom_id;input.name=f.custom_id;input.placeholder=f.placeholder||'';input.value=f.value||'';input.required=!!f.required;input.maxLength=f.max_length||4000;const label=el('label','',f.label);label.htmlFor=f.custom_id;fields.append(label,input);}}$('#modal-error').textContent='';if(!$('#advanced').open)$('#advanced').showModal();}
$('#advanced-form').onsubmit=e=>{e.preventDefault();const values=Object.fromEntries(new FormData(e.target));$('#advanced').close();act({action:'modal',values});};$('#cancel-modal').onclick=()=>$('#advanced').close();$('#scenario').onchange=()=>reset();$('#reset').onclick=()=>reset();$('#focus').onclick=()=>reset(true);$('#narrow').onchange=()=>$('#discord').classList.toggle('narrow',$('#narrow').checked);$('#race').onclick=()=>act({action:'race'});$('#inject-error').onclick=()=>render({...snapshot,error:true,message:'Simulated query interruption. Your previous menu remains available.'});$('#inspect').onclick=()=>{$('#payload-text').textContent=JSON.stringify({...snapshot,files:Object.fromEntries(Object.keys(snapshot?.files||{}).map(k=>[k,'<local generated image>']))},null,2);$('#payload-dialog').showModal();};$('#close-payload').onclick=()=>$('#payload-dialog').close();document.addEventListener('click',e=>{const link=e.target.closest('#message a');if(link){e.preventDefault();if(!link.classList.contains('v2-button'))$('#message').prepend(el('div','notice','This is a synthetic match ID. Live match links are disabled in the offline lab.'));}if(!e.target.closest('.v2-select')){document.querySelectorAll('.select-menu').forEach(m=>m.hidden=true);document.querySelectorAll('.select-trigger').forEach(t=>t.setAttribute('aria-expanded','false'));}});reset(new URLSearchParams(location.search).get('focus')==='1',new URLSearchParams(location.search).get('scenario')||'normal');
